language: cpp

dist: xenial

# Branch whitelist.
branches:
  only:
    - master

addons:
  apt:
    sources:
    - sourceline: "deb https://apt.kitware.com/ubuntu/ xenial main"
      key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
    - cmake

# Choose operating systems.
os:
  - linux
  - osx

# Choose compilers.
compiler:
  - clang
  - gcc

# XXX: HACK to select the correct CMake/CTest binary.
before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      export CMAKE=/usr/bin/cmake; export CTEST=/usr/bin/ctest;
    else
      export CMAKE=cmake; export CTEST=ctest;
    fi
  - wget https://gist.githubusercontent.com/jiverson002/f5f6db706b69cf0cd0975848bbf5ecb7/raw/dev-buildconfig

# Override default script.
script:
  - $CMAKE -DEFIKA_BUILDCONFIG_FILE=dev-buildconfig . && $CMAKE --build . && $CTEST --output-on-failure
