language: cpp

dist: xenial

# Branch whitelist.
branches:
  only:
    - master

addons:
  apt:
    sources:
    - sourceline: "deb https://apt.kitware.com/ubuntu/ xenial main"
      key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
    - cmake

# Choose operating systems.
os:
  - linux
  - osx

# Choose compilers.
compiler:
  - clang
  - gcc

# Override default script.
script:
  - /usr/bin/cmake . && /usr/bin/cmake --build . && /usr/bin/ctest --output-on-failure
